# config.py  프레임 설정
WALK_FRAME_WIDTH = 45
WALK_FRAME_HEIGHT = 150

WALK_RIGHT_FRAME_WIDTH = 45  # 오른쪽 걷기 프레임 너비
WALK_RIGHT_FRAME_HEIGHT = 150  # 오른쪽 걷기 프레임 높이

IDLE_FRAME_WIDTH = 40
IDLE_FRAME_HEIGHT = 150